apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: zabbix
  labels:
    app: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-mysql:ubuntu-7.0-latest@sha256:b14d5350b439ad6d0c8c0a2c96e3dd10aa460a228bfd18a2971aab8bb6bbf619
        ports:
        - containerPort: 10051
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-secret
              key: zabbix_mariadb_root_password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: zabbix-secret
              key: zabbix_mariadb_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-secret
              key: zabbix_mariadb_password
        - name: MYSQL_DATABASE
          value: zabbix
        - name: DB_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: zabbix-configmap
              key: database_url
